yamllint
Change-Id: I94c4245037c58df958a95e6fca977ae678315fbc

diff --git a/.github/workflows/codeql.yml b/.github/workflows/codeql.yml
--- a/.github/workflows/codeql.yml
+++ b/.github/workflows/codeql.yml
@@ -1,3 +1,4 @@
+---
 # scilab/.github/workflows/codeql.yml: GitHub Actions CodeQL workflow for scilab
 # For most projects, this workflow file will not need changing; you simply need
 # to commit it to your repository.
@@ -31,8 +32,9 @@ jobs:
     #   - https://gh.io/recommended-hardware-resources-for-running-codeql
     #   - https://gh.io/supported-runners-and-hardware-resources
     #   - https://gh.io/using-larger-runners (GitHub.com only)
-    # Consider using larger runners or machines with greater resources for possible analysis time improvements.
-    runs-on: ${{ (matrix.language == 'swift' && 'macos-latest') || 'ubuntu-latest' }}
+    # Consider using larger runners or machines with greater resources for
+    # possible analysis time improvements.
+    runs-on: 'ubuntu-latest'
     timeout-minutes: ${{ (matrix.language == 'swift' && 120) || 360 }}
     permissions:
       # required for all workflows
@@ -49,85 +51,99 @@ jobs:
       fail-fast: false
       matrix:
         include:
-        - language: csharp
-          build-mode: none
-        - language: java-kotlin
-          build-mode: none # This mode only analyzes Java. Set this to 'autobuild' or 'manual' to analyze Kotlin too.
-        # CodeQL supports the following values keywords for 'language':
-        # 'c-cpp', 'csharp', 'go', 'java-kotlin', 'javascript-typescript', 'python', 'ruby', 'swift'
-        # Use `c-cpp` to analyze code written in C, C++ or both
-        # Use 'java-kotlin' to analyze code written in Java, Kotlin or both
-        # Use 'javascript-typescript' to analyze code written in JavaScript, TypeScript or both
-        # To learn more about changing the languages that are analyzed or customizing the build mode for your analysis, see:
-        # https://docs.github.com/en/code-security/code-scanning/creating-an-advanced-setup-for-code-scanning/customizing-your-advanced-setup-for-code-scanning
-        # If you are analyzing a compiled language, you can modify the 'build-mode' for that language to customize how your codebase is analyzed, see:
-        # https://docs.github.com/en/code-security/code-scanning/creating-an-advanced-setup-for-code-scanning/codeql-code-scanning-for-compiled-languages
+          - language: csharp
+            build-mode: none
+          - language: java-kotlin
+            build-mode: none  # This mode only analyzes Java, which is ok here.
+            # CodeQL supports the following values keywords for 'language':
+            # 'c-cpp', 'csharp', 'go', 'java-kotlin', 'javascript-typescript',
+            # 'python', 'ruby', 'swift'
+            # Use `c-cpp` to analyze code written in C, C++, or both
+            # Use 'java-kotlin' to analyze code written in Java, Kotlin, or both
+            # Use 'javascript-typescript' to analyze code written in JavaScript,
+            # TypeScript, or both
+            # To learn more about changing the languages that are analyzed or
+            # customizing the build mode for your analysis, see:
+            # https://docs.github.com/en/code-security/code-scanning/creating-an-advanced-setup-for-code-scanning/customizing-your-advanced-setup-for-code-scanning
+            # If you are analyzing a compiled language, you can modify the
+            # 'build-mode' for that language to customize how your codebase is
+            # analyzed, see:
+            # https://docs.github.com/en/code-security/code-scanning/creating-an-advanced-setup-for-code-scanning/codeql-code-scanning-for-compiled-languages
     steps:
-    - name: Checkout repository
-      uses: actions/checkout@v4
+      - name: Checkout repository
+        uses: actions/checkout@v4
 
-    - name: Dependencies
-      if: matrix.language == 'c-cpp'
-      run: |
-        sudo apt-get -qq update
-        sudo apt-get install libc6-dev-amd64-cross libgcc-s1-amd64-cross gobjc gobjc-multilib libfl-dev libtbb-dev autopoint libhdf5-dev h5utils hdf5-tools libjhdf5-java libjhdf5-jni libhe5-hdfeos-dev libpdl-io-hdf5-perl hdf5-helpers python3-h5py ruby-hdfeos5 libsis-jhdf5-jni libsis-jhdf5-java libpbihdf-dev python3-hdf5storage hdf-compass libhdf5-jni libhdf5-java libhdf4-dev hdf4-tools libextutils-f77-perl scilab scilab-include
+      - name: Dependencies
+        if: matrix.language == 'c-cpp'
+        run: |
+          sudo apt-get -qq update
+          sudo apt-get install libc6-dev-amd64-cross libgcc-s1-amd64-cross \
+            gobjc gobjc-multilib libfl-dev libtbb-dev autopoint libhdf5-dev \
+            h5utils hdf5-tools libjhdf5-java libjhdf5-jni libhe5-hdfeos-dev \
+            libpdl-io-hdf5-perl hdf5-helpers python3-h5py ruby-hdfeos5 \
+            libsis-jhdf5-jni libsis-jhdf5-java libpbihdf-dev \
+            python3-hdf5storage hdf-compass libhdf5-jni libhdf5-java \
+            libhdf4-dev hdf4-tools libextutils-f77-perl scilab scilab-include
 
-    # Initializes the CodeQL tools for scanning.
-    - name: Initialize CodeQL
-      uses: github/codeql-action/init@v3
-      with:
-        languages: ${{ matrix.language }}
-        build-mode: ${{ matrix.build-mode }}
-        # If you wish to specify custom queries, you can do so here or in a config file.
-        # By default, queries listed here will override any specified in a config file.
-        # Prefix the list here with "+" to use these queries and those in the config file.
+      # Initializes the CodeQL tools for scanning.
+      - name: Initialize CodeQL
+        uses: github/codeql-action/init@v3
+        with:
+          languages: ${{ matrix.language }}
+          build-mode: ${{ matrix.build-mode }}
+          # If you wish to specify custom queries, you can do so here or in a
+          # config file.
+          # By default, queries listed here will override any specified in a
+          # config file.
+          # Prefix the list here with "+" to use these queries and those in the
+          # config file.
 
-        # For more details on CodeQL's query packs, refer to:
-        # https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-code-scanning#using-queries-in-ql-packs
-        # queries: security-extended,security-and-quality
+          # For more details on CodeQL's query packs, refer to:
+          # https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-code-scanning#using-queries-in-ql-packs
+          # queries: security-extended,security-and-quality
 
-    # If the analyze step fails for one of the languages you are analyzing with
-    # "We were unable to automatically build your code", modify the matrix above
-    # to set the build mode to "manual" for that language. Then modify this step
-    # to build your code.
-    # Command-line programs to run using the OS shell; see:
-    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsrun
-    - name: Manual build message
-      if: matrix.build-mode == 'manual'
-      shell: bash
-      run: |
-        echo ''
-        echo 'If you are using a "manual" build mode for one or more of the' \
-          'languages you are analyzing, replace this with the commands to build' \
-          'your code, for example:'
-        echo '  make bootstrap'
-        echo '  make release'
-        exit 1
+      # If the analyze step fails for 1 of the languages you are analyzing with
+      # "We were unable to automatically build your code", modify the matrix
+      # above to set the build mode to "manual" for that language. Then modify
+      # this step to build your code.
+      # Command-line programs to run using the OS shell; see:
+      # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsrun
+      - name: Manual build message
+        if: matrix.build-mode == 'manual'
+        shell: bash
+        run: |
+          echo ''
+          echo 'If you are using a "manual" build mode for one or more of the' \
+            'languages you are analyzing, replace this with the commands to' \
+            'build your code, for example:'
+          echo '  make bootstrap'
+          echo '  make release'
+          exit 1
 
-    - name: Perform CodeQL Analysis
-      uses: github/codeql-action/analyze@v3
-      with:
-        category: "/language:${{matrix.language}}"
+      - name: Perform CodeQL Analysis
+        uses: github/codeql-action/analyze@v3
+        with:
+          category: "/language:${{matrix.language}}"
 
-    - name: Debug failure
-      if: matrix.language == 'c-cpp' && failure()
-      run: |
-        sync && (stat config.log || stat scilab/config.log) && sync
-        find . -name config.log -print0 | xargs -0 cat
-        sync && sleep 1
-        if test -x "$(which locate)"; then \
-          which locate && locate hdf5.h; \
-        elif test -x "$(which glocate)"; then \
-          which glocate && glocate hdf5.h; \
-        elif test -x "$(which mlocate)"; then \
-          which mlocate && mlocate hdf5.h; \
-        elif test -x "$(which plocate)"; then \
-          which plocate && plocate hdf5.h; \
-        elif test -x "$(which find)"; then \
-          sync && echo "using $(which find) to attempt to find hdf5.h"; \
-          find / -name hdf5.h -print -perm +r -user "$(whoami)" 2>/dev/null; \
-        elif test -x "$(which gfind)"; then \
-          which gfind && gfind / -name hdf5.h -print; \
-        else \
-          ls -R; \
-        fi
+      - name: Debug failure
+        if: matrix.language == 'c-cpp' && failure()
+        run: |
+          sync && (stat config.log || stat scilab/config.log) && sync
+          find . -name config.log -print0 | xargs -0 cat
+          sync && sleep 1
+          if test -x "$(which locate)"; then \
+            which locate && locate hdf5.h; \
+          elif test -x "$(which glocate)"; then \
+            which glocate && glocate hdf5.h; \
+          elif test -x "$(which mlocate)"; then \
+            which mlocate && mlocate hdf5.h; \
+          elif test -x "$(which plocate)"; then \
+            which plocate && plocate hdf5.h; \
+          elif test -x "$(which find)"; then \
+            sync && echo "using $(which find) to attempt to find hdf5.h"; \
+            find / -name hdf5.h -print -perm +r -user "$(whoami)" 2>/dev/null; \
+          elif test -x "$(which gfind)"; then \
+            which gfind && gfind / -name hdf5.h -print; \
+          else \
+            ls -R; \
+          fi
